apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketing

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - api-config.yaml
  - api.yaml
